"""
Django settings for 233spider project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import posixpath

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zw^t3gu5fq@ea!&5sd)x7brageh(g@7apd-!s6*86#m15uhs-z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spider.apps.SpiderConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '233spider.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '233spider.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'spider',
        'USER': 'bing',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'
STATIC_ROOT = 'static/'
IMAGE_COLLECT_FOLDER = 'images/analysis'
IMAGE_TITLE_FOLDER = 'images/title'
HERDER = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
}
CHROMEDRIVER = posixpath.join(BASE_DIR, 'chromedriver.exe')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# 用户名和密码
ACCOUNT = '13324430205'
PASSWORD = 'linux0105'

# 是否开启代理
PROXY = False
# 获取ip地址的url
IPPOOL = None

# 隐藏界面
HEADLESS = False

# CATEGORY = [1188, 1189, 1266, 1196, 1197, 1289, 1263, 1265, 533, 534, 880, 384, 385, 386, 751, 752, 1247, 1200, 1201, 1248, 1429, 1285, 1311, 1321, 190, 189, 191, 353, 356, 358, 354, 357, 1139, 1140, 1142, 194, 195, 214, 369, 370, 371, 372, 373, 375, 376, 377, 378, 379, 40, 41, 45, 1345, 1344, 43, 44, 1322, 1323, 208, 209, 210, 1352, 1353, 1354, 1355, 1356, 1357, 211, 169, 172, 171, 1382, 1383, 174, 1379, 1380, 569, 992, 1431, 1365, 1366, 1367, 1221, 1376, 1377, 1371, 1372, 1373, 1368, 1369, 1370, 1154, 1012, 774, 772, 773, 778, 799, 779, 792, 1161, 1162, 1163, 1160, 1185, 912, 913, 914, 915, 1202, 1203, 1245, 1204, 1243, 1244, 1215, 1217, 1210, 1246, 1211, 1284, 1237, 1267, 1268, 1269, 1206, 1271, 1272, 1300, 1273, 1274, 1275, 1276, 1316, 1302, 916, 919, 1363, 1364, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1410, 1409, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1390, 997, 999, 993, 994, 1068, 996, 1000, 1066, 995, 998, 1261, 1262, 1287, 626, 627, 1288, 624, 625, 521, 522, 524, 525, 540, 1361, 1330, 1347, 1331, 1332, 1328, 1327, 1326, 1329, 1346, 1333, 1334, 1348, 1336, 1335, 1338, 1337, 1342, 1341, 1339, 1340, 183, 1264, 1292, 1291, 1295, 1297, 1349, 1350, 1258, 29, 32, 33, 35, 38, 81, 83, 84, 86, 89, 584, 638, 639, 640, 641, 1158, 421, 423, 428, 447, 443, 446, 444, 445, 448, 451, 1374, 426, 429, 430, 431, 634, 1386, 1387, 285, 286, 566, 567, 803, 1130, 1017, 240, 246, 247, 248, 266, 256, 1016, 1015, 100, 133, 125, 1019, 1070, 1022, 308, 309, 311, 218, 307, 310, 228, 922, 923, 1359, 1360, 572, 573, 574, 575, 585, 652, 653, 654, 655, 656, 576, 577, 578, 586, 587, 588]

CATEGORY = [752]